INSERT INTO Categorias VALUES(1,"Bebidas","Gaseosas, café, té, cervezas y maltas"); 
INSERT INTO Categorias VALUES(2,"Condimentos","Salsas dulces y picantes, delicias, comida para untar y aderezos");
INSERT INTO Categorias VALUES(3,"Repostería","Postres, dulces y pan dulce");
INSERT INTO Categorias VALUES(4,"Lácteos","Quesos");
INSERT INTO Categorias VALUES(5,"Granos/Cereales","Pan, galletas, pasta y cereales");
INSERT INTO Categorias VALUES(6,"Carnes","Carnes preparadas");
INSERT INTO Categorias VALUES(7,"Frutas/Verduras","Frutas secas y queso de soja");
INSERT INTO Categorias VALUES(8,"Pescado/Marisco","Pescados, mariscos y algas");
INSERT INTO Productos VALUES(1,1,"Té Dharamsala","10 cajas x 20 bolsas",34);
INSERT INTO Productos VALUES(2,1,"Cerveza tibetana","24 - bot. 12 l",23);
INSERT INTO Productos VALUES(3,2,"Sirope de regaliz","12 - bot. 550 ml",12);
INSERT INTO Productos VALUES(4,2,"Especias Cajun del chef Anton New","48 - frascos 6 l",23);
INSERT INTO Productos VALUES(5,2,"Mezcla Gumbo del chef Anton","Condimentos 36 cajas",34);
INSERT INTO Productos VALUES(6,2,"Mermelada de grosellas de la abuela","12 - frascos 8 l",45);
INSERT INTO Productos VALUES(7,7,"Peras secas orgánicas del tío Bob ","12 - paq. 1 kg",23);
INSERT INTO Productos VALUES(14,7,"Cuajada de judías Mayumi's","40 - paq. 100 g",60);
INSERT INTO Productos VALUES(9,6,"Buey Mishi Kobe Tokyo Traders","18 - paq. 500 g",23);
INSERT INTO Productos VALUES(17,6,"Cordero Alice Springs Pavlova, Ltd.","20 - latas 1 kg",10);
INSERT INTO Productos VALUES(11,4,"Queso Cabrales Cooperativa de Quesos","paq. 1 kg",12);
INSERT INTO Productos VALUES(12,4,"Queso Manchego La Pastora Cooperativa","10 - paq. 500 g",10);
INSERT INTO Productos VALUES(10,8,"Pez espada Tokyo Traders","12 - frascos 200 ml",56);
INSERT INTO Productos VALUES(13,8,"Algas Konbu Mayumi's","caja 2 kg",45);
INSERT INTO Productos VALUES(18,8,"Langostinos tigre Carnarvon","paq. 16 kg",35);
INSERT INTO Productos VALUES(16,3,"Postre de merengue Pavlova Pavlova, Ltd.","32 - cajas 500g",25);
INSERT INTO Productos VALUES(19,3,"Pastas de té de chocolate 12 piezas","10 cajas x 12 piezas", 45);
INSERT INTO Productos VALUES(20,3,"Mermelada de Sir Rodney's Specialty","30 cajas regalo",15);
